version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    networks:
      - wordpress-net
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=1234"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Limita a 1 CPU
          memory: 1G  # Limita a memória a 1GB
        reservations:
          cpus: "0.5"  # Reserva 0.5 CPU
          memory: 512M  # Reserva 512MB de memória

  php-fpm:
    image: php-fpm
    container_name: php-fpm
    networks:
      - wordpress-net
    volumes:
      - wordpress_data:/usr/share/nginx/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb  # Garante que o mariadb seja iniciado antes do php-fpm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Limita a 1 CPU
          memory: 1G  # Limita a memória a 1GB
        reservations:
          cpus: "0.5"  # Reserva 0.5 CPU
          memory: 512M  # Reserva 512MB de memória

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - wordpress-net
    volumes:
      - wordpress_data:/usr/share/nginx/html
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - php-fpm  # Garante que o php-fpm seja iniciado antes do nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Limita a 0.5 CPU
          memory: 512M  # Limita a memória a 512MB
        reservations:
          cpus: "0.25"  # Reserva 0.25 CPU
          memory: 256M  # Reserva 256MB de memória

networks:
  wordpress-net:
    driver: bridge

volumes:
  wordpress_data:
